### ISSUE TITLE
CR/LF aren't stripped from Line fields

### ISSUE THREAD

**Issue by tsdko** [liamzdenek/go-irc#6]
This means (in case of the RSS bot) it's possible to execute arbitrary IRC commands when a `<title>` or `<link>` tag contains newlines.

Workaround for the bot available at https://github.com/tsudoko/go-irc/tree/sanitization.

Possible real fix: make `irc.NewLine()` take struct fields from `Line` as arguments, strip `\r` and `\n` and make the bot use `NewLine()` instead of constructing the `Line` directly. The existing `NewLine()` function could be renamed to `LineFromRaw()`.

**Comment by liamzdenek** [comment]
See PR #7, comments?
